export const OPCIONES_SUCURSAL_CENTRO = [
  "Casa Matriz",
  "Sucursal Puerto Montt",
  "Sucursal Antofagasta",
  "Sucursal Talca",
  "Sucursal Centro Puerto",
  "Sucursal Cambio y Soluciones (Peru)",
  "Sucursal Valparaiso",
  "Sucursal Copiapo",
] as const;

export const OPCIONES_AREA_CENTRO = [
  "GERENCIA COMERCIAL",
  "GERENCIA DE CAMIONES",
  "GERENCIA ADM. Y FINANZAS",
  "GERENCIA POST VENTA",
  "GERENCIA REPUESTOS",
  "GERENCIA OPERACIONES",
  "GERENCIA GENERAL",
] as const;

export const OPCIONES_CENTRO_COSTO_CENTRO = [
  "GERENCIA GENERAL",
  "GERENCIA ADM. Y FINANZAS",
  "GERENCIA COMERCIAL CAMIONES",
  "GERENCIA COMERCIAL BUSES",
  "GERENCIA NUEVOS NEGOCIOS",
  "GERENCIA OPERACIONES",
  "GERENCIA POST VENTA",
  "CONTABILIDAD",
  "CRÉDITO Y COBRANZA",
  "FISCALIA",
  "INFORMÁTICA",
  "MANTENIMIENTO Y SSGG",
  "RECURSOS HUMANOS",
  "TESORERÍA",
  "NUEVOS NEGOCIOS",
  "NEGOCIOS BUSES USADOS",
  "NEGOCIOS BUSES NUEVOS",
  "SERVICIOS GENERALES",
  "SOPORTE COMERCIAL",
  "ASISTENCIA TÉCNICA",
  "CARROCERÍA",
  "DESABOLLADURA Y PINTURA",
  "DIESEL",
  "ELECTROMOVILIDAD",
  "TALLER MECÁNICO",
  "BODEGA",
  "COMPRAS REPUESTOS",
  "VENTAS REPUESTOS",
] as const;

export const OPCIONES_ROL_CENTRO = [
  "admin",
  "gerente",
  "jefe",
  "vendedor",
  "tecnico",
  "usuarioGeneral",
  "chofer",
  "subBodega",
  "usuarioCredito",
  "analistaCredito",
  "adminCredito",
  "gerentenv",
  "contanv",
  "cobranzanv",
  "gerentebnnv",
  "gerentebunv",
  "gerentecanv",
  "vendedorcanv",
  "cambiosnv",
  "licitacionnv",
  "preFacturacion",
  "facturacion",
  "taller",
  "multinvsr",
  "multinvjr",
  "traslados",
  "revisionnv",
  "usrconta",
  "jfconta",
  "contabilidadtkt",
  "contabilidadtktjf",
  "tesoreriatkt",
  "tesoreriatktjf",
  "recursoshumanostkt",
  "recursoshumanostktjf",
  "cobranzatkt",
  "cobranzatktjf",
  "informaticatkt",
  "informaticatktjf",
  "soportecomercialtkt",
  "soportecomercialtktjf",
  "asistenciatecnicatkt",
  "asistenciatecnicatktjf",
  "bodegatkt",
  "bodegatktjf",
  "gcamionestkt",
  "gcamionestktjf",
] as const;

export const OPCIONES_PERMISOS_APP_STOCK = [
  "stock",
  "reportes-reservas",
  "calendario-entregas",
  "admin-panel",
] as const;

export const ROL_INICIAL_USUARIO = "usuarioGeneral";
export const PASSWORD_MIN_LENGTH = 6;
export const PAGE_SIZE_USUARIOS = 12;
